server:
  servlet:
    contextPath: /muay-thai-service
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/NewsAgency
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/master/master-changelog.yml
